# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: antibiogram_ocr.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x61ntibiogram_ocr.proto\x12\x0f\x61ntibiogram_ocr\"\"\n\x0cImageRequest\x12\x12\n\nimage_data\x18\x01 \x01(\x0c\"\x1b\n\x0bOCRResponse\x12\x0c\n\x04text\x18\x01 \x01(\t2W\n\nOCRService\x12I\n\nPerformOCR\x12\x1d.antibiogram_ocr.ImageRequest\x1a\x1c.antibiogram_ocr.OCRResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'antibiogram_ocr_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_IMAGEREQUEST']._serialized_start=42
  _globals['_IMAGEREQUEST']._serialized_end=76
  _globals['_OCRRESPONSE']._serialized_start=78
  _globals['_OCRRESPONSE']._serialized_end=105
  _globals['_OCRSERVICE']._serialized_start=107
  _globals['_OCRSERVICE']._serialized_end=194
# @@protoc_insertion_point(module_scope)
