# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import antibiogram_ocr_pb2 as antibiogram__ocr__pb2


class OCRServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PerformOCR = channel.unary_unary(
                '/antibiogram_ocr.OCRService/PerformOCR',
                request_serializer=antibiogram__ocr__pb2.ImageRequest.SerializeToString,
                response_deserializer=antibiogram__ocr__pb2.OCRResponse.FromString,
                )


class OCRServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def PerformOCR(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OCRServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PerformOCR': grpc.unary_unary_rpc_method_handler(
                    servicer.PerformOCR,
                    request_deserializer=antibiogram__ocr__pb2.ImageRequest.FromString,
                    response_serializer=antibiogram__ocr__pb2.OCRResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'antibiogram_ocr.OCRService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class OCRService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def PerformOCR(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/antibiogram_ocr.OCRService/PerformOCR',
            antibiogram__ocr__pb2.ImageRequest.SerializeToString,
            antibiogram__ocr__pb2.OCRResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
